FROM python:3.11-slim

RUN pip install --upgrade pip && pip install pipenv

WORKDIR /app

COPY Pipfile Pipfile.lock ./

RUN pipenv install --system --deploy --ignore-pipfile

COPY . .

EXPOSE 8000

CMD ["gunicorn", "--bind", "0.0.0.0:$PORT", "app:app"]
